### ISSUE TITLE
video?

### ISSUE THREAD

**Issue by jsonberry** [wardbell/rxjs-in-ng#1]
@wardbell Thanks for posting this, looking forward to checking it out. Do you know if there was a video of the talk? I checked the AngularMIX youtube channel here https://www.youtube.com/channel/UCnUpEUN4V3iJxoUximdr6Nw/videos but I didn't see one.

**Comment by inorganik** [comment]
Here you go: https://www.youtube.com/watch?v=q--U25yPTrA

**Comment by SanderElias** [comment]
@jsonberry, there was no video on our AngularMix iteration, there is one now, from mostly the same talk we did on ngConf, as helpfully posted by @inorganik.
BTW if you want the source version of the angularMix version, you should be looking in at: https://github.com/SanderElias/AngularMix2017Demo

**Comment by jsonberry** [comment]
Thanks all, much appreciated!
