### ISSUE TITLE
Doesn't build - missing deps

### ISSUE THREAD

**Issue by inorganik** [wardbell/rxjs-in-ng#4]
Looks like there's a couple deps missing (fails to build). I couldn't find these on npm:

```ts
import { OnoffbuttonModule } from 'onoffbutton';
import { SeNeonModule } from 'se-neon';
```

cc @SanderElias 

Thanks!

**Comment by SanderElias** [comment]
I'll need to address this in the readme, start with a `ng build`, this will build the libraries. 
this is because of a known issue in the cli-6. will probably be fixed before 6 is out.

**Comment by SanderElias** [comment]
@inorganik I added a post-install step that addresses this issue. 
Thanks for bringing my attention back to this.
